"""Rust-backed daemon cycle policy (single Python surface)."""

from __future__ import annotations

from greenfloor.core.cycle._bridge_managed import (
    can_parallelize_managed_offers,
    classify_dexie_visibility_outcome,
    classify_managed_post_result,
    count_parallel_transient_failures,
    expand_planned_actions,
    filter_planned_actions_with_positive_repeat,
    is_transient_dexie_visibility_404_error,
    is_transient_managed_upstream_error_text,
    managed_retry_decision,
    parallel_max_workers,
    plan_parallel_managed_dispatch,
    reservation_release_status,
    sequential_action_route,
    should_apply_parallel_transient_cooldown,
    single_input_preferred_skip_reason,
)
from greenfloor.core.cycle._bridge_orchestration import (
    classify_dexie_stale_offer_status,
    collect_stale_sweep_candidates,
    dedupe_sorted_market_ids,
    enqueue_immediate_requeue,
    evaluate_market,
    evaluate_two_sided_market_actions,
    is_dexie_offer_missing_error_text,
    is_two_sided_market_mode,
    needs_inventory_fallback,
    next_disabled_market_log_deadline,
    record_stale_sweep_check,
    select_market_batch,
    should_log_disabled_market,
    should_try_cat_inventory_fallback,
    should_use_market_slot_dispatch,
)
from greenfloor.core.cycle.policy import (
    aggregate_two_sided_offer_counts,
    apply_offer_signal_payload,
    classify_managed_transient_error,
    empty_stale_sweep_payload,
    evaluate_market_payload,
    executed_sell_offer_counts_by_size,
    expiry_seconds_for_action,
    is_managed_upstream_transient_error,
    is_managed_worker_transient_error,
    is_parallel_dispatch_transient_error,
    one_sided_offer_counts_by_side,
    plan_reseed_actions_from_gap,
    resolve_inventory_scan_source,
    resolve_tracked_sizes,
    size_counts_to_signer,
)
from greenfloor.core.cycle_reseed import ReseedGapPlan, ReseedSkipReason
from greenfloor.core.kernel_bridge import import_kernel


def market_cycle_phases() -> tuple[str, ...]:
    return tuple(import_kernel().market_cycle_phases())


MARKET_CYCLE_PHASES: tuple[str, ...] = market_cycle_phases()

__all__ = [
    "MARKET_CYCLE_PHASES",
    "aggregate_two_sided_offer_counts",
    "apply_offer_signal_payload",
    "can_parallelize_managed_offers",
    "classify_dexie_stale_offer_status",
    "classify_dexie_visibility_outcome",
    "classify_managed_post_result",
    "classify_managed_transient_error",
    "collect_stale_sweep_candidates",
    "count_parallel_transient_failures",
    "dedupe_sorted_market_ids",
    "empty_stale_sweep_payload",
    "enqueue_immediate_requeue",
    "evaluate_market",
    "evaluate_market_payload",
    "evaluate_two_sided_market_actions",
    "executed_sell_offer_counts_by_size",
    "expand_planned_actions",
    "expiry_seconds_for_action",
    "filter_planned_actions_with_positive_repeat",
    "is_dexie_offer_missing_error_text",
    "is_managed_upstream_transient_error",
    "is_managed_worker_transient_error",
    "is_parallel_dispatch_transient_error",
    "is_transient_dexie_visibility_404_error",
    "is_transient_managed_upstream_error_text",
    "is_two_sided_market_mode",
    "managed_retry_decision",
    "market_cycle_phases",
    "needs_inventory_fallback",
    "next_disabled_market_log_deadline",
    "one_sided_offer_counts_by_side",
    "plan_reseed_actions_from_gap",
    "parallel_max_workers",
    "ReseedGapPlan",
    "ReseedSkipReason",
    "plan_parallel_managed_dispatch",
    "record_stale_sweep_check",
    "reservation_release_status",
    "resolve_inventory_scan_source",
    "resolve_tracked_sizes",
    "select_market_batch",
    "sequential_action_route",
    "should_apply_parallel_transient_cooldown",
    "should_log_disabled_market",
    "should_try_cat_inventory_fallback",
    "should_use_market_slot_dispatch",
    "single_input_preferred_skip_reason",
    "size_counts_to_signer",
]
