"""Minimal signer program.yaml for offer asset resolution tests."""


def write_signer_program_yaml(
    path,
    *,
    home_dir: str,
    msp_base_url: str,
) -> None:
    path.write_text(
        "\n".join(
            [
                "app:",
                '  network: "mainnet"',
                f'  home_dir: "{home_dir}"',
                "runtime:",
                "  loop_interval_seconds: 30",
                "chain_signals:",
                "  tx_block_trigger:",
                "    webhook_enabled: true",
                '    webhook_listen_addr: "127.0.0.1:8787"',
                "dev:",
                "  python:",
                '    min_version: "3.11"',
                "notifications:",
                "  low_inventory_alerts:",
                "    enabled: true",
                '    threshold_mode: "absolute_base_units"',
                "    default_threshold_base_units: 0",
                "    dedup_cooldown_seconds: 60",
                "    clear_hysteresis_percent: 10",
                "  providers:",
                "    - type: pushover",
                "      enabled: true",
                '      user_key_env: "PUSHOVER_USER_KEY"',
                '      app_token_env: "PUSHOVER_APP_TOKEN"',
                '      recipient_key_env: "PUSHOVER_RECIPIENT_KEY"',
                "venues:",
                "  dexie:",
                '    api_base: "https://api.dexie.space"',
                "  splash:",
                '    api_base: "http://localhost:4000"',
                "  offer_publish:",
                '    provider: "dexie"',
                "signer:",
                '  kms_key_id: "arn:aws:kms:us-west-2:123:key/demo"',
                '  kms_region: "us-west-2"',
                '  kms_public_key_hex: "020202020202020202020202020202020202020202020202020202020202020202"',
                f'  coinset_msp_base_url: "{msp_base_url}"',
                "vault:",
                '  launcher_id: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"',
                "  custody_threshold: 1",
                "  recovery_threshold: 1",
                "  recovery_clawback_timelock: 3600",
                "  custody_keys:",
                '    - public_key_hex: "020202020202020202020202020202020202020202020202020202020202020202"',
                "      curve: SECP256R1",
                "  recovery_keys:",
                '    - public_key_hex: "ab3cb61463a695fa094f7c30526c8097fb813a0c5fa67bab261a7cd354cb6363b2d726218135b25b814f94df4749fc58"',
                "      curve: BLS12_381",
            ]
        ),
        encoding="utf-8",
    )
